sudo: false
language: csharp
solution: RedisContext.sln
services:
  - redis-server
before_install:
  - git clone https://github.com/StackExchange/StackExchange.Redis.git
  - xbuild /p:Configuration=Release ./StackExchange.Redis/StackExchange.Redis/StackExchange.Redis.csproj
install:
  - nuget restore RedisContext.sln
  - nuget install xunit.runners -Version 1.9.2 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release RedisContext.sln
  - cp ./StackExchange.Redis/StackExchange.Redis/bin/Release/StackExchange.Redis.dll ./RedisContextTests/bin/Release/
  - mono ./testrunner/xunit.runners.1.9.2/tools/xunit.console.clr4.exe ./RedisContextTests/bin/Release/RedisContextTests.dll