language: csharp
solution: RedisContext.sln
services:
  - redis-server
install:
  - nuget restore RedisContext.sln
  - nuget install xunit.runners -Version 1.9.2 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release RedisContext.sln
  - mono ./testrunner/xunit.runners.1.9.2/tools/xunit.console.clr4.exe ./RedisContextTests/bin/Release/RedisContextTests.dll